version: '3'

aria2:
  image: ndthuan/aria2-alpine
  volumes:
    - /tmp/Downloads:/downloads
  ports:
    - '6800:6800'
  networks:
    - aria2-net

httpd:
  image: busybox
  volumes:
    - ./:/usr/html
  ports:
    - '80:80/tcp'
  networks:
    - aria2-net
  command: /bin/busybox httpd -f -p 80 -h /usr/html

networks:
  ? aria2-net
